#!/bin/bash
#
# Starts an HTTP server serving the files in this directory.
#
HALCOWEB_DIR="$(cd "$(dirname "$0")" && pwd -P)"
cd $HALCOWEB_DIR
echo "Starting server in directory `pwd`"
echo "Please visit http://localhost:8000 in your browser"
exec python -m SimpleHTTPServer